version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: build_push_image
          command: |
             if [ "${CIRCLE_BRANCH}" == "docker_image_update" ]; then
                echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
                docker build -t ashot90docker/qa-task:latest .
                docker push ashot90docker/qa-task:latest
             fi
      - run:
          name: pull_image
          command: |
              if [ "${CIRCLE_BRANCH}" != "docker_image_update" ]; then
                 docker pull ashot90docker/qa-task:latest
              fi
      - run:
          name: run_tests
          command: docker run -it --env BROWSER=Firefox --env PORTAL='DE' --env PARALLEL=true ashot90docker/qa-task
